version: 2

project_name: driftlens

before:
  hooks:
    - go mod tidy

builds:
  - id: driftlens
    main: ./cmd/driftlens
    binary: driftlens
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}

archives:
  - id: driftlens
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - id: driftlens-amd64
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "hardikaws/driftlens:{{ .Version }}-amd64"
    build_flag_templates:
      - --platform=linux/amd64

  - id: driftlens-arm64
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "hardikaws/driftlens:{{ .Version }}-arm64"
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: "hardikaws/driftlens:{{ .Version }}"
    image_templates:
      - "hardikaws/driftlens:{{ .Version }}-amd64"
      - "hardikaws/driftlens:{{ .Version }}-arm64"
  - name_template: "hardikaws/driftlens:latest"
    image_templates:
      - "hardikaws/driftlens:{{ .Version }}-amd64"
      - "hardikaws/driftlens:{{ .Version }}-arm64"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
